# Generated by Django 4.2.16 on 2025-04-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20250405_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
