# Generated by Django 4.2.16 on 2025-04-05 20:30

from django.db import migrations

from datetime import datetime
from django.db import migrations

def extract_release_date(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        release_data = movie.releaseDetailed
        if release_data:
            date_str = release_data.get("date")
            if date_str:
                try:
                    # Handles ISO 8601 format: "2022-04-27T00:00:00.000Z"
                    parsed_date = datetime.fromisoformat(date_str.replace("Z", "+00:00")).date()
                    movie.created = parsed_date
                    movie.save(update_fields=["releaseDate"])
                except Exception as e:
                    # Optional: log or print for debugging
                    print(f"Failed to parse date for movie ID {movie.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_movie_created'),
    ]

    operations = [
         migrations.RunPython(extract_release_date),
    ]
