# Generated by Django 4.2.16 on 2025-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20250406_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_star',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
