# Generated by Django 4.2.16 on 2025-04-06 08:30

from django.db import migrations
def extract_star_rating(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        rating = movie.rating
        if rating:
            star_rating = rating.get("star")
            if star_rating:
                try:
                    # Handles ISO 8601 format: "2022-04-27T00:00:00.000Z"
                    movie.rating_star = star_rating
                    movie.save(update_fields=["rating_star"])
                except Exception as e:
                    # Optional: log or print for debugging
                    print(f"Failed to update rating_star for movie ID {movie.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_movie_rating_star'),
    ]

    operations = [
        migrations.RunPython(extract_star_rating)

    ]
