# Generated by Django 4.2.16 on 2025-04-09 06:35

from django.db import migrations


def extract_count_rating(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        rating = movie.rating
        if rating:
            count_rating = rating.get("count")
            if count_rating:
                try:
                    # Handles ISO 8601 format: "2022-04-27T00:00:00.000Z"
                    movie.rating_count = count_rating
                    movie.save(update_fields=["rating_count"])
                except Exception as e:
                    # Optional: log or print for debugging
                    print(
                        f"Failed to update rating_count for movie ID {movie.id}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_movie_rating_count'),
    ]

    operations = [
        migrations.RunPython(extract_count_rating)
    ]
