# Generated by Django 4.2.16 on 2025-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20250409_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='nominations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
