# Generated by Django 4.2.16 on 2025-04-09 06:44

from django.db import migrations

def extract_awards(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        award = movie.award
        if award:
            wins = award.get("wins")
            nominations = award.get("nominations")
            if wins:
                try:
                    movie.wins = wins
                    movie.save(update_fields=["wins"])
                except Exception as e:
                    print(
                        f"Failed to update wins for movie ID {movie.id}: {e}")
            if nominations:
                try:
                    movie.nominations = nominations
                    movie.save(update_fields=["nominations"])
                except Exception as e:
                    print(
                        f"Failed to update nominations for movie ID {movie.id}: {e}")
                    
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_movie_nominations_movie_wins'),
    ]

    operations = [
        migrations.RunPython(extract_awards)
    ]
