# Generated by Django 4.2.16 on 2025-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20250409_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='releaseLocation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
