# Generated by Django 4.2.16 on 2025-04-09 06:58

from django.db import migrations

def extract_releaseLocation(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        releaseDetailed = movie.releaseDetailed
        if releaseDetailed:
            releaseLocation = releaseDetailed.get("releaseLocation")
            if releaseLocation:
                try:
                    # Handles ISO 8601 format: "2022-04-27T00:00:00.000Z"
                    movie.releaseLocation = releaseLocation
                    movie.save(update_fields=["releaseLocation"])
                except Exception as e:
                    # Optional: log or print for debugging
                    print(f"Failed to update releaseLocation for movie ID {movie.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_movie_releaselocation'),
    ]

    operations = [
        migrations.RunPython(extract_releaseLocation)
    ]
