# Generated by Django 4.2.16 on 2025-04-09 07:23

from django.db import migrations
import ast

def extract_releaseLocation(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        releaseLocationString = movie.releaseLocation
        if releaseLocationString:            
                try:
                    value = ast.literal_eval(releaseLocationString)
                    releaseLocation = value
                    if isinstance(value, dict):
                        releaseLocation = value.get("country")
                    releaseLocation = ast.literal_eval(releaseLocationString).get("country")
                    if releaseLocation:
                        movie.releaseLocation = releaseLocation
                        movie.save(update_fields=["releaseLocation"])
                except Exception as e:
                    print(f"Failed to update releaseLocation for movie ID {movie.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20250409_1020'),
    ]

    operations = [
        migrations.RunPython(extract_releaseLocation)
    ]
