# Generated by Django 4.2.16 on 2025-04-09 07:34

from django.db import migrations
import ast


def extract_releaseLocation(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        releaseLocationString = movie.releaseLocation
        if releaseLocationString:
            try:
                releaseLocation = ast.literal_eval(
                    releaseLocationString).get("country")
                if releaseLocation:               
                        movie.releaseLocation = releaseLocation
                        movie.save(update_fields=["releaseLocation"])
            except Exception as e:
                print(
                    f"Failed to update releaseLocation for movie ID {movie.id}: {e}")                        



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20250409_1023'),
    ]

    operations = [
        migrations.RunPython(extract_releaseLocation)
    ]
