# Generated by Django 4.2.16 on 2025-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20250409_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='releaseDetailed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
