# Generated by Django 4.2.16 on 2025-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_movie_releasedetailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
