# Generated by Django 4.2.16 on 2025-04-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
