# Generated by Django 4.2.16 on 2025-04-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_sguser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created',
            new_name='created_date',
        ),
    ]
