# Generated by Django 4.2.16 on 2025-04-14 10:16

from django.db import migrations, models
import datetime


def copy_created_date_to_created(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        if movie.created_date and not movie.created:
            movie.created = datetime.datetime.combine(movie.created_date, datetime.time.min)
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_created_movie_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(copy_created_date_to_created),
    ]
