# Generated by Django 4.2.16 on 2025-04-19 04:27

from django.db import migrations


def change_backend_domain(apps, schema_editor):
    Movie = apps.get_model('base', 'Movie')
    for movie in Movie.objects.all():
        stream_link = movie.stream
        if stream_link:
            try:
                movie.stream = stream_link.replace("sguploads.atongjona.com", "backend.streamgrid.stream")
                movie.save(update_fields=["stream"])
            except Exception as e:
                # Optional: log or print for debugging
                print(
                    f"Failed to update stream for movie ID {movie.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_movie_created'),
    ]

    operations = [
        migrations.RunPython(change_backend_domain)
    ]
