# Generated by Django 4.2.16 on 2025-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20250419_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='dropped',
            field=models.ManyToManyField(blank=True, related_name='dropped', to='base.movie'),
        ),
        migrations.AddField(
            model_name='sguser',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='finished', to='base.movie'),
        ),
        migrations.AddField(
            model_name='sguser',
            name='hold',
            field=models.ManyToManyField(blank=True, related_name='hold', to='base.movie'),
        ),
        migrations.AddField(
            model_name='sguser',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='plan', to='base.movie'),
        ),
    ]
