# Generated by Django 4.2.16 on 2025-05-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_historyitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyitem',
            old_name='currentAt',
            new_name='current_at',
        ),
    ]
