# Generated by Django 4.2.16 on 2025-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_currentat_historyitem_current_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='downloaded',
            field=models.ManyToManyField(blank=True, related_name='downloaded', to='base.movie'),
        ),
    ]
